
app:
  replicaCount: 2  # Two replicas for prod availability

database:
  name: proddb
  username: produser

postgresql:
  auth:
    existingSecret: platform-prod-db-secret
    username: produser
    database: proddb
  primary:
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
    persistence:
      size: 10Gi  # Slightly larger for prod
