
app:
  replicaCount: 1  # Single replica for dev

database:
  name: devdb
  username: devuser

postgresql:
  image:
    tag: "16"
  auth:
    existingSecret: platform-dev-db-secret
    username: devuser
    database: devdb
  primary:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 250m
        memory: 384Mi
    persistence:
      size: 5Gi
