
app:
  replicaCount: 1  # Single replica for preprod

database:
  name: preproddb
  username: preproduser

postgresql:
  image:
    tag: "16"
  auth:
    existingSecret: platform-preprod-db-secret
    username: preproduser
    database: preproddb
  primary:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 300m
        memory: 512Mi
    persistence:
      size: 5Gi
