apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  labels:
    app: {{ .Values.app.name }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  postgres-password: {{ .Values.database.password }}
  password: {{ .Values.database.password }}
  replication-password: {{ .Values.database.password }}
  database-name: {{ .Values.database.name }}
  database-username: {{ .Values.database.username }}
